export const data = [
  {
    id: "1",
    key: "1",
    channel: "PDF",
    document: "Ant Design",
    group: "Receipts",
    status: "Received",
    date: "2021-02-28",
    type: "Prior",
    address: <a href="/">/localhost</a>,
  },
  {
    id: "2",
    key: "2",
    channel: "SMS",
    document: "Bnt Design",
    group: "Fintech",
    status: "Printed",
    date: "2021-02-06",
    type: "Registr",
    address: <a href="/">/dwww</a>,
  },
  {
    id: "3",
    key: "3",
    channel: "SMS",
    document: "Cnt Design",
    group: "Users",
    status: "Folded",
    date: "2021-02-07",
    type: "Non-Prior",
    address: <a href="/">c/www</a>,
  },
  {
    id: "4",
    key: "4",
    channel: "PDF",
    document: "Dnt Design",
    group: "RRHH",
    status: "Sorted",
    date: "2021-02-08",
    type: "Registr",
    address: <a href="/">sales/y</a>,
  },
  {
    id: "5",
    key: "5",
    channel: "PDF",
    document: "Ent Design",
    group: "Deparment",
    status: "Delivered",
    date: "2021-02-09",
    type: "Registr",
    address: <a href="/">route/q</a>,
  },
  {
    id: "6",
    key: "6",
    channel: "SMS",
    document: "Fnt Design",
    group: "Programers",
    status: "Received",
    date: "2021-02-10",
    type: "Non-Prior",
    address: <a href="/">address/w</a>,
  },
  {
    id: "7",
    key: "7",
    channel: "PDF",
    document: "Gnt Design",
    group: "Sales",
    status: "Delivered",
    date: "2021-02-11",
    type: "Registr",
    address: <a href="/">/localhost/etc</a>,
  }
];
